import { MD3DarkTheme, MD3LightTheme } from 'react-native-paper';
import materialTheme from './material-theme.json';

const lightScheme = materialTheme.schemes.light;
const darkScheme = materialTheme.schemes.dark;

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: lightScheme.primary,
    onPrimary: lightScheme.onPrimary,
    primaryContainer: lightScheme.primaryContainer,
    onPrimaryContainer: lightScheme.onPrimaryContainer,
    secondary: lightScheme.secondary,
    onSecondary: lightScheme.onSecondary,
    secondaryContainer: lightScheme.secondaryContainer,
    onSecondaryContainer: lightScheme.onSecondaryContainer,
    tertiary: lightScheme.tertiary,
    onTertiary: lightScheme.onTertiary,
    background: lightScheme.background,
    onBackground: lightScheme.onBackground,
    surface: lightScheme.surface,
    onSurface: lightScheme.onSurface,
    surfaceBright: lightScheme.surfaceBright,
    onSurfaceBright: lightScheme.onSurfaceBright,
    surfaceContainerLow: lightScheme.surfaceContainerLow,
    onSurfaceContainerLow: lightScheme.onSurfaceContainerLow,
    surfaceContainerLowest: lightScheme.surfaceContainerLowest,
    onSurfaceContainerLowest: lightScheme.onSurfaceContainerLowest,
    inverseSurface: lightScheme.inverseSurface,
    inverseOnSurface: lightScheme.inverseOnSurface,
    error: lightScheme.error,
    onError: lightScheme.onError,
    success: lightScheme.success,
    onSuccess: lightScheme.onSuccess,
    successContainer: lightScheme.successContainer,
    onSuccessContainer: lightScheme.onSuccessContainer,
    surfaceVariant: lightScheme.surfaceVariant,
    onSurfaceVariant: lightScheme.onSurfaceVariant,
    outline: lightScheme.outline,
    outlineVariant: lightScheme.outlineVariant,
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: darkScheme.primary,
    onPrimary: darkScheme.onPrimary,
    primaryContainer: darkScheme.primaryContainer,
    onPrimaryContainer: darkScheme.onPrimaryContainer,
    secondary: darkScheme.secondary,
    onSecondary: darkScheme.onSecondary,
    secondaryContainer: darkScheme.secondaryContainer,
    onSecondaryContainer: darkScheme.onSecondaryContainer,
    tertiary: darkScheme.tertiary,
    onTertiary: darkScheme.onTertiary,
    background: darkScheme.background,
    onBackground: darkScheme.onBackground,
    surface: darkScheme.surface,
    onSurface: darkScheme.onSurface,
    surfaceBright: darkScheme.surfaceBright,
    onSurfaceBright: darkScheme.onSurfaceBright,
    surfaceContainerLow: darkScheme.surfaceContainerLow,
    onSurfaceContainerLow: darkScheme.onSurfaceContainerLow,
    surfaceContainerLowest: darkScheme.surfaceContainerLowest,
    onSurfaceContainerLowest: darkScheme.onSurfaceContainerLowest,
    inverseSurface: darkScheme.inverseSurface,
    inverseOnSurface: darkScheme.inverseOnSurface,
    error: darkScheme.error,
    onError: darkScheme.onError,
    success: darkScheme.success,
    onSuccess: darkScheme.onSuccess,
    successContainer: darkScheme.successContainer,
    onSuccessContainer: darkScheme.onSuccessContainer,
    surfaceVariant: darkScheme.surfaceVariant,
    onSurfaceVariant: darkScheme.onSurfaceVariant,
    outline: darkScheme.outline,
    outlineVariant: darkScheme.outlineVariant,
  },
};